edecasa/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('products.urls'),name='products'),
    #path('perfil/', include('accounts.urls'),name='profile'),
    #path('pedido/', include('orders.urls'),name='order'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/',include(debug_toolbar.urls))
    ]

orders/urls.py
from django.urls import path

url_patterns = [

]

products/urls.py
from django.urls import path
from .views import HomeProductListView,ProductDetailView
app_name = 'products'

urlpatterns = [
    path('', HomeProductListView.as_view(), name='home'),
    path('<slug>', ProductDetailView.as_view(),name='detail'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ValidationError
from utils import validate


class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField()
    cpf = models.PositiveBigIntegerField()
    address = models.CharField(max_length=50)
    house_number = models.CharField(max_length=30)
    address_complement = models.CharField(max_length=255)
    cep = models.PositiveIntegerField()

    def __str__(self):
        return self.user.username

    def clean(self):
        error_messages = {}
        if not validate.validate_cpf(self.cpf):
            error_messages['cpf'] = 'Digite um CPF válido.'
        if not validate.validate_cep(self.cep):
            error_messages['cep'] = 'Digite um CEP válido.'
        if error_messages:
            raise ValidationError(error_messages)

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product
from uuid import uuid4

class Order(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False, unique=True)
    user = models.ForeignKey(User,on_delete= models.CASCADE)
    price = models.FloatField()
    status = models.CharField(
        max_length=2,
        choices = (
            ('C', 'Completo'),
            ('AP','Aguardando Pagamento'),
            ('P','Processando'),
            ('E','Enviado'),
            ('CN','Cancelado')
        )
    )
    def __str__(self):
        return str(self.id)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

products/models.py
from django.db import models
from django.utils.text import slugify
from uuid import uuid4
from PIL import Image
from os.path import join
from django.conf import settings


class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "categories"

class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False, unique=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True, null=True)
    base_price = models.FloatField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images')
    second_image = models.ImageField(upload_to='product_images', blank=True)
    third_image = models.ImageField(upload_to='product_images', blank=True)
    fourth_image = models.ImageField(upload_to='product_images', blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):

        def optimize_image(image):
            image_path = join(settings.MEDIA_ROOT, image.name)
            image_pillow = Image.open(image_path)
            image_pillow.save(image_path, optime=True, quality=85)

        def resize_image(image):
            max_image_width, max_image_height = (640, 640)
            image_path = join(settings.MEDIA_ROOT, image.name)
            image_pillow = Image.open(image_path)
            image_width, image_height = image_pillow.size
            if image_width != max_image_width or image_height != max_image_height:
                resized_image = image_pillow.resize((max_image_width, max_image_height), Image.LANCZOS)
                resized_image.save(image_path)

        if not self.slug:
            self.slug = slugify(self.name) + str(self.pk)

        super().save(*args, **kwargs)
        for image in [self.image, self.second_image, self.third_image, self.fourth_image]:
            if image:
                optimize_image(image)
                resize_image(image)





class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    price = models.FloatField()
    stock_quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render

# Create your views here.

orders/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .models import Product

class HomeProductListView(ListView):
    model = Product
    template_name = 'products/home.html'
    context_object_name = 'products'
    queryset = Product.objects.values('slug', 'name', 'base_price', 'image')[:9]

class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/detail.html'
    context_object_name = 'product'
    slug_url_kwarg = 'slug'

    def get_object(self):
        product = super(ProductDetailView, self).get_object()
        return product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        images = [product.image, product.second_image, product.third_image, product.fourth_image]
        context['product_images'] = list(filter(None, images))
        return context

products/templates/products/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="single-product-area section-padding-100 clearfix">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb mt-50">
                        <li class="breadcrumb-item"><a href="{% url 'products:home' %}">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">{{ product.category }}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{{ product.name }}</li>
                    </ol>
                </nav>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-7">
                <div class="single_product_thumb">
                    <div id="product_details_slider" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            {% for product_image in product_images %}
                                {% if forloop.counter0 == 0 %}
                                    <li class="active" data-target="#product_details_slider" data-slide-to="{{ forloop.counter0 }}" style="background-image: url({{ product_image.url }});"></li>
                                {% else %}
                                    <li data-target="#product_details_slider" data-slide-to="{{ forloop.counter0 }}" style="background-image: url({{ product_image.url }});"></li>
                                {% endif %}
                            {% endfor %}
                        </ol>
                        <div class="carousel-inner">

                            {% for product_image in product_images %}
                                {% if forloop.counter0 == 0 %}
                                    <div class="carousel-item active">
                                {% else %}
                                    <div class="carousel-item">
                                {% endif %}
                                <a class="gallery_img" href="{{ product_image.url }}">
                                    <img class="d-block w-100" src="{{ product_image.url }}" alt="Slide">
                                </a>
                            </div>
                            {% endfor %}


                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-5">
                <div class="single_product_desc">
                    <!-- Product Meta Data -->
                    <div class="product-meta-data">
                        <div class="line"></div>
                        <p class="product-price">R$ {{ product.base_price }}</p>
                        <a href="product-details.html">
                            <h6>{{ product.name }}</h6>
                        </a>
                        <!-- Ratings & Review -->
                        <div class="ratings-review mb-15 d-flex align-items-center justify-content-between">
                            <div class="ratings">
                                <i class="fa fa-star" aria-hidden="true"></i>
                                <i class="fa fa-star" aria-hidden="true"></i>
                                <i class="fa fa-star" aria-hidden="true"></i>
                                <i class="fa fa-star" aria-hidden="true"></i>
                                <i class="fa fa-star" aria-hidden="true"></i>
                            </div>
                            <div class="review">
                                <a href="#">Write A Review</a>
                            </div>
                        </div>
                        <!-- Avaiable -->
                        <p class="avaibility"><i class="fa fa-circle"></i> Em Estoque</p>
                    </div>

                    <div class="short_overview my-5">
                        <p>{{ product.description }}</p>
                    </div>

                    <!-- Add to Cart Form -->
                    <form class="cart clearfix" method="post">
                        {% csrf_token %}

                        <select name="select" id="product-variations">
                            {% for product_variation in product.variation_set.all %}
                                <option value="value">{{ product_variation.name }}</option>
                            {% endfor %}

                        </select>

                        <div class="cart-btn d-flex mb-50" >
                            <p>Qtd</p>
                            <div class="quantity" >
                                <span class="qty-minus" onclick="var effect = document.getElementById('qty'); var qty = effect.value; if( !isNaN( qty ) &amp;&amp; qty &gt; 1 ) effect.value--;return false;"><i class="fa fa-caret-down" aria-hidden="true"></i></span>
                                <input type="number" class="qty-text" id="qty" step="1" min="1" max="5" name="quantity" value="1">
                                <span class="qty-plus" onclick="var effect = document.getElementById('qty'); var qty = effect.value; if( !isNaN( qty )) effect.value++;return false;"><i class="fa fa-caret-up" aria-hidden="true"></i></span>
                            </div>
                        </div>
                        <button type="submit" name="addtocart" value="5" class="btn amado-btn">Add to cart</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="products-catagories-area clearfix">
    <div class="amado-pro-catagory clearfix">

        <!-- Single Catagory -->
        {% for product in products%}
        <div class="single-products-catagory clearfix">
            <a href="{% url 'products:detail' product.slug %}">
                {% if product.image %}
                <img src="media/{{ product.image }}" alt="">
                {% else %}
                <img src="{% static 'assets/img/product-img/suspiros_amarelo.jpg' %}" alt="">
                {% endif %}
                <!-- Hover Content -->
                <div class="hover-content">
                    <div class="line"></div>
                    <p>Por R${{ product.base_price }}</p>
                    <h4>{{ product.name }}</h4>
                </div>
            </a>
        </div>
        {% endfor %}

    </div>
</div>
        <!-- Product Catagories Area End -->
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'partials/_head.html' %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% include 'partials/search.html' %}
    <!-- Search Wrapper Area End -->

    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix">


        {% include 'partials/mobile_nav.html' %}
        {% include 'partials/_header.html' %}

        {% block content %}{% endblock %}
    </div>

    {% include 'partials/_section.html' %}
    {% include 'partials/_footer.html' %}

</body>
</html>

templates/partials/_footer.html
{% load static %}
<footer class="footer_area clearfix">
    <div class="container">
        <div class="row align-items-center">
            <!-- Single Widget Area -->
            <div class="col-12 col-lg-4">
                <div class="single_widget_area">
                    <!-- Logo -->
                    <div class="footer-logo mr-50">
                        <a href="index.html"><img src="{% static 'assets/img/core-img/logo2.png' %}" alt=""></a>
                    </div>
                    <!-- Copywrite Text -->
                    <p class="copywrite"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a> & Re-distributed by <a href="https://themewagon.com/" target="_blank">Themewagon</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
            </div>
            <!-- Single Widget Area -->
            <div class="col-12 col-lg-8">
                <div class="single_widget_area">
                    <!-- Footer Menu -->
                    <div class="footer_menu">
                        <nav class="navbar navbar-expand-lg justify-content-end">
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                            <div class="collapse navbar-collapse" id="footerNavContent">
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item active">
                                        <a class="nav-link" href="index.html">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="shop.html">Shop</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="product-details.html">Product</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="cart.html">Cart</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="checkout.html">Checkout</a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- ##### Footer Area End ##### -->

<!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->
<script src="{% static 'assets/js/jquery/jquery-2.2.4.min.js' %}"></script>
<!-- Popper js -->
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<!-- Bootstrap js -->
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<!-- Plugins js -->
<script src="{% static 'assets/js/plugins.js' %}"></script>
<!-- Active js -->
<script src="{% static 'assets/js/active.js' %}"></script>

templates/partials/_head.html
{% load static %}
<meta name="description" content="">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

<!-- Title  -->
<title>Amado - Furniture Ecommerce Template | Product Details</title>

<!-- Favicon  -->
<link rel="icon" href="{% static 'assets/img/core-img/favicon.ico' %}">

<!-- Core Style CSS -->
<link rel="stylesheet" href="{% static 'assets/css/core-style.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

templates/partials/_header.html
{% load static %}
<!-- Header Area Start -->
<header class="header-area clearfix">
    <!-- Close Icon -->
    <div class="nav-close">
        <i class="fa fa-close" aria-hidden="true"></i>
    </div>
    <!-- Logo -->
    <div class="logo">
        <a href="{% url 'products:home' %}"><img src="{% static 'assets/img/core-img/logo.png' %}" alt=""></a>
    </div>
    <!-- Amado Nav -->
    <nav class="amado-nav">
        <ul>
            <li><a href="{% url 'products:home' %}">Início</a></li>
            <li class="active"><a href="shop.html">Doces</a></li>
            <li><a href="cart.html">Carrinho</a></li>
            <li><a href="checkout.html">Fechar Pedido</a></li>
        </ul>
    </nav>
    <!-- Button Group -->
    <div class="amado-btn-group mt-30 mb-100">
        <a href="#" class="btn amado-btn mb-15">%Discount%</a>
        <a href="#" class="btn amado-btn active">New this week</a>
    </div>
    <!-- Cart Menu -->
    <div class="cart-fav-search mb-100">
        <a href="cart.html" class="cart-nav"><img src="{% static 'assets/img/core-img/cart.png' %}" alt=""> Cart <span>(0)</span></a>
        <a href="#" class="fav-nav"><img src="{% static 'assets/img/core-img/favorites.png' %}" alt=""> Favourite</a>
        <a href="#" class="search-nav"><img src="{% static 'assets/img/core-img/search.png' %}" alt=""> Search</a>
    </div>
    <!-- Social Button -->
    <div class="social-info d-flex justify-content-between">
        <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
    </div>
</header>

templates/partials/_section.html
<section class="newsletter-area section-padding-100-0">
    <div class="container">
        <div class="row align-items-center">
            <!-- Newsletter Text -->
            <div class="col-12 col-lg-6 col-xl-7">
                <div class="newsletter-text mb-100">
                    <h2>Subscribe for a <span>25% Discount</span></h2>
                    <p>Nulla ac convallis lorem, eget euismod nisl. Donec in libero sit amet mi vulputate consectetur. Donec auctor interdum purus, ac finibus massa bibendum nec.</p>
                </div>
            </div>
            <!-- Newsletter Form -->
            <div class="col-12 col-lg-6 col-xl-5">
                <div class="newsletter-form mb-100">
                    <form action="#" method="post">
                        <input type="email" name="email" class="nl-email" placeholder="Your E-mail">
                        <input type="submit" value="Subscribe">
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

templates/partials/mobile_nav.html
{% load static %}
<!-- Mobile Nav (max width 767px)-->
<div class="mobile-nav">
    <!-- Navbar Brand -->
    <div class="amado-navbar-brand">
        <a href="{% url 'products:home' %}"><img src="{% static 'assets/img/core-img/logo.png' %}" alt=""></a>
    </div>
    <!-- Navbar Toggler -->
    <div class="amado-navbar-toggler">
        <span></span><span></span><span></span>
    </div>
</div>

templates/partials/search.html
{% load static %}
<div class="search-wrapper section-padding-100">
    <div class="search-close">
        <i class="fa fa-close" aria-hidden="true"></i>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="search-content">
                    <form action="#" method="get">
                        <input type="search" name="search" id="search" placeholder="Type your keyword...">
                        <button type="submit"><img src="{% static 'assets/img/core-img/search.png' %}" alt=""></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>